### ISSUE TITLE
Solution for 18-string-api.js not functioning properly

### ISSUE THREAD

**Issue by abdaahads** [gitabdulahad/PGDAC-Assignments#2]
output is not visible on the connected HTML Page

**Comment by totally-somesh** [comment]
Please assign this issue to me.

**Comment by abdaahads** [comment]
Alright!! Issue assigned to @totally-somesh

**Comment by abdaahads** [comment]
Based on your work on #1 I would like to see how you approach this problem

**Comment by totally-somesh** [comment]
#2 Issue Resolved. Please Check.
